### ISSUE TITLE
Negotiation algorithm is not ideal

### ISSUE THREAD

**Issue by yoavweiss** [w3c/IFT#107]
Patch-subset-first requests have some costs, in the sense that they are optimistically uploading the patch.

It'd be better to have an [ALPS](https://www.ietf.org/archive/id/draft-vvv-httpbis-alps-01.html) frame that would opt in to patch-subset as part of the connection establishment to let the browser know of patching support ahead of request-sending time.

Squinting at this (a bit hard, admittedly), one can imagine patch-subsetting as some sort of a [Client Hint](https://github.com/WICG/client-hints-infrastructure/blob/main/README.md). It doesn't fully fit, as the server we want to opt-in to client hints here is not the top-level origin, but one of its font servers, and ALPS opt-in only works at the top-level origin.
But there are certainly parallels, and I can imagine y'all building something that is client-hint-like, with the right characteristics to solve this particular content negotiation problem.

I'm happy to advise on that front, if that's helpful.

**Comment by garretrieger** [comment]
Thanks, I'm not too familiar with ALPS, so I'll review that and see if it looks like a better fit for doing the negotiation. It would be great if we could avoid sending the uneeded PatchRequest to a range request only server (so long as we're not adding any extra round trips to do so).

**Comment by garretrieger** [comment]
I've reviewed ALPS and I have a couple concerns:
1. Since ALPS is part of TLS it works at the connection level. Connections are made to a specific domain and under that domain there may more than one actual servers processing requests depending on the specific patch requested. Having a frame in ALPS that opts in to patch subset would opt int all paths under that domain, which in many cases may not be ideal (eg. a CDN which serves assets for many different users from the same domain).
2. Using ALPS could complicate implementations where SSL termination is not happening at the same place where the HTTP request is being processed. Again thinking of the example where SSL termination is happening at a single place for a domain but specific paths under that domain are served by completely different servers.

I think then if we want to go down this path, we should make the use of a SETTING via ALPS optional. That is, define a server sent SETTING which instructs the client to only use range request. If the client does not receive that setting it will use the currently specified behaviour of including the PatchRequest message in the first request + fallback to range request depending on the server's response. If it does receive the setting then the client would omit the PatchRequest message from the first request. This then gives a mechanism to servers that don't support patch subset to have clients avoid sending them an unnecessary PatchRequest. 

The good news is it looks like we are free define custom setting identifier under HTTP3 (https://www.rfc-editor.org/rfc/rfc9114.html#name-defined-settings-parameters) as an extension.

@litherum do you have any thoughts?

**Comment by garretrieger** [comment]
Should be fixed by #113. Please reopen if you still have concerns with the new method negotiation introduced by that PR.

**Comment by garretrieger** [comment]
Completely agreed.
