### ISSUE TITLE
Can't generate html

### ISSUE THREAD

**Issue by skef** [w3c/IFT#143]
I'm trying to generate HTML for the current main branch and am seeing fatal errors along the lines of:

```
bikeshed spec Overview.bs
LINE ~301: Couldn't find section '#name-get' in spec 'rfc9110':
[[rfc9110#name-get]]
 ✘  Did not generate, due to fatal errors
make: *** [Makefile:4: Overview.html] Error 2
```

However, at least informally it does seem like rfc9110 has a heading with that id, and more generally `bikeshed` documentation is pretty sparse on what it's doing and how one would go about fixing these. Any guidance?

**Comment by skef** [comment]
Hmm, I guess the `-f` flag works for this. I'll leave this open as there do seem to be dangling references now.

**Comment by garretrieger** [comment]
I ran into this recently as well, something seems to have changed in bikeshed at the latest version. For now I've been able to get it to compile without errors using bikeshed 3.10.0. I'll look into this a bit more and see if it's something we're doing wrong or if it's an issue with bikeshed.

**Comment by tidoust** [comment]
As mentioned in the Bikeshed's issue, this is due to the switch to Webref for xref data. Webref currently uses `httpwg.org` URLs for IETF RFCs developed by the HTTP Working Group, and fragment IDs are not the same in the `httpwg.org` version compared with the `rfc-editor.org` version.

Now, please hold on updating the fragment IDs, we're re-evaluating switching back to `rfc-editor.org` URLs for RFC9110 in Webref. The use of `httpwg.org` URLs is a good idea for older RFCs as the `rfc-editor.org` URL is not as usable, but not really needed for more recent RFCs.

I keep you updated (I need to evaluate what specs would need to be updated if we switch back to `rfc-editor.org` URLs)

**Comment by tidoust** [comment]
Quick status update: Webref (and Bikeshed) xref data now contains headings from the `rfc-editor.org`. Unfortunately, I'm afraid that's not going to solve your linking errors because, in Webref, the IDs that get extracted for headings are the IDs of the wrapping sections when they exist, and not the IDs of the heading elements themselves.

So, typically, you'd have to use `rfc9110#section-9.3.1` and not `rfc9110#name-get` to link to [section 9.3.1 GET](https://www.rfc-editor.org/rfc/rfc9110#section-9.3.1). I don't know why these RFCs contain 2 IDs for essentially the same thing.

**Comment by garretrieger** [comment]
Thanks for the updates, I'll update our references to use the new IDs.
