### ISSUE TITLE
Rewrite explainer

### ISSUE THREAD

**Issue by svgeesus** [w3c/IFT#160]
The [current explainer](https://github.com/w3c/IFT/blob/main/Patch-Subset-Explainer.md) will need to be totally re-written. There is no longer a need to explain why we have patch-subset and range-request; but there is now a need to explain why there are two patch formats, for example.

**Comment by yisibl** [comment]
> Complete rewrite of the specification. Separate 'Patch Subset' and 'Range Request' methods have been removed in favour of a single unified approach.

Yes, I'd love to know the story behind what happened with the new specs and the pros and cons of merging them together.

**Comment by yisibl** [comment]
> https://lists.w3.org/Archives/Public/public-webfonts-wg/2023Sep/0003.html
Have the problems mentioned here been solved?

As a CJK font service provider, I strongly support iconfont.co.uk if the server-side deployment is beneficial to the performance improvement of subsetized fonts. 

As a matter of fact, we have already deployed server-side interfaces to implement subsetting of CJK fonts, but the way we implement it is that the user inputs a text, and we return a subsetized buffer of the text.

**Comment by vlevantovsky** [comment]
> Have the problems mentioned here been solved?

I believe you will find useful information and answers to some of your questions in these presentation slides: [Static_Incremental_Font_Transfer.pdf](https://lists.w3.org/Archives/Public/public-webfonts-wg/2023Oct/att-0006/Static_Incremental_Font_Transfer.pdf)

**Comment by garretrieger** [comment]
The main motivation for pivoting away from requiring the dynamic backend server is that would have placed too big a burden on adopters of the technology. Also the dynamic approach was fairly difficult to cache efficiently, and there were significant concerns with it's ability to scale as a result (see: https://github.com/w3c/IFT/issues/119). With the new approach we now have an embedded map to the patch URLs within the font file, this gives much more flexibility for how the patches are hosted. You can either host them as static files on a standard http server, or if desired dynamically generate the patches on demand. Because the embedded URL's can contain opaque string tokens you could in theory embed a base64 encoded message just like the old PatchRequest inside of URLs to drive dynamic generation. I plan to put together a demo of this at some point to demonstrate it's viability.

The main trade-off that gets made for this new approach is that the patches potentially become less granular. Under the old approach you could have patch requests made for the exact combination of codepoints on the current page. Under the new approach you're now requesting all groups that intersect the content. The proof of concept ([demo](https://garretrieger.github.io/ift-demo/) shows that this can still generate transfer sizes significantly less than just breaking up the font and serving with unicode range. It's probably also important to note that in practice with the previous approach, most real implementations likely would have ended up using similar levels of granularity (via over delivering codepoints in responses) as the new approach in order to achieve acceptable levels of caching.

**Comment by yisibl** [comment]
If the new approach is easier to get off the ground, that would indeed be an advantage.
At first glance, this seems somewhat similar to what Google fonts are doing now: slicing the font into many, only with the addition of map mapping. (Please correct me if I'm not understanding this correctly).

So what tool is used to slice these fonts now? I can't wait to try it out.


In our usage scenario, the text is entered by the user in real-time, so I would also like to have this test to see how fast the new method is?

> Because the embedded URL's can contain opaque string tokens you could in theory embed a base64 encoded message just like the old PatchRequest inside of URLs to drive dynamic generation. I plan to put together a demo of this at some point to demonstrate it's viability.

I look forward to this demo.

**Comment by garretrieger** [comment]
> If the new approach is easier to get off the ground, that would indeed be an advantage. At first glance, this seems somewhat similar to what Google fonts are doing now: slicing the font into many, only with the addition of map mapping. (Please correct me if I'm not understanding this correctly).
> 

That's right, there's a couple of key advantages to this approach vs the "unicode-range" approach we use today:
1. When each slice is a separate font there's a significant amount of overhead per slice due to the font format (1-2kb). This effectively limits how small you can make each slice. With a patch based approach this is avoided and you can have very small slices (eg. 10 codepoints per slice vs 100 with unicode range) without per slice overhead making it extremely inefficient.
2. Because patches are used to build up a single font versus having many small individual fonts you can have codepoints split across slices that interact via layout rules. So for example you can split up latin codepoints into multiple slices but still have kerning work correctly across all of those codepoints. This also allows for much smaller slices than with unicode range where interacting codepoints need to be kept together.
3. unicode-range can only pick slices based on codepoints, with IFT we gain the ability to pick slices based on VF design space and layout features as well.

> So what tool is used to slice these fonts now? I can't wait to try it out.

We have some very early prototypes at the moment (they are a little clunky atm, something that I hope to improve soon):
1. https://github.com/adobe/binned-ift-reference: this is an encoder for binned ift (a precursor to the current spec), it can take a font and some configuration and find a segmentation of it for you.
2. https://github.com/w3c/patch-subset-incxfer/blob/main/util/font2ift.cc: this util can take a font and a binned ift segmentation (from 1) as an input and convert it to a IFT font that's compatible with the current spec.

These two tools are what was used to produce the fonts for the demo I linked. At some point in the future I'll be merging the functionality from 1 into 2. So it'll just be one util that you can point at a font and have it produce an IFT encoded font.
