### ISSUE TITLE
Alternative high-level breakdown of patch extension algorithm

### ISSUE THREAD

**Issue by skef** [w3c/IFT#239]
We've already discussed changing the current description so that instead of creating a single list of patches, we create lists by invalidation status: full, partial, or no. When we discussed this the idea was to process them in that order. We've also discussed using the order of entries in the map for tie breaking, so we'll probably want to say that when the patches are broken out into these lists the ordering must be preserved.

In addition to that, I propose that we change the description to say that the list of full invalidation patches (if any) must be processed *first*. Then, once there are no remaining intersecting full invalidation patches, the remaining two lists can be processed *concurrently*. This makes the nature of partial invalidation patches clear in the algorithm and is better relative to the concerns of [this thread](https://github.com/w3c/IFT/pull/237#discussion_r1844900800).

**Comment by garretrieger** [comment]
I experimented with a few different ways of approaching this and settled on #244. The approach I ended up going with is adding an explicit step to the extension algorithm that instructs the client to start loads for any entries which won't be invalidated by the current selection. The reason I did it this way is:

- Patch application by it's nature is will always be done serially so I want to keep the extension algorithm with one patch application per iteration as it's currently written.
- However, patch loads are free to run concurrently so that's what I addressed vs making the high level processing concurrent as suggested in this issue.
- As discussed in [this comment](https://github.com/w3c/IFT/issues/240#issuecomment-2489640938) we can't always blindly load all no invalidation patches when processing a partial invalidation patch. Instead the correct thing to do is to start loads for all things that you can see won't be invalidated by the current selection.
- Performance concerns in #232 are resolved by instructing the client to skip redundant intersection checks.

Overall I believe this addresses the concerns raised here and related issues:
- We now have clear and simple guidance for what should be concurrently fetched, providing clarity for encoder implementations so they will be able to predict what will actually happen in an optimized client implementation.
- This guidance respects the invalidation behaviour as currently defined.
- Improved clarity for how processing prioritizes invalidation types by grouping entries by invalidation type prior to selection.

**Comment by garretrieger** [comment]
Should be addressed by the #244, but feel free to reopen if more is needed.
