### ISSUE TITLE
Considerations for multiple distinct servers in patch-subset method

### ISSUE THREAD

**Issue by litherum** [w3c/IFT#29]
As dynamic content is added to the page, there will be multiple requests to the server. However, because of server load balancing, each of those requests might end up going to a different physical server running different software.

If every server used for incrementally updating the existing subset has to be running the exact same software as the server used for creating the first subset (to make sure the subsetted files match what was previously sent to the client), that would be fairly brittle. Often, when large server farms have their software updated, the machines are updated a few at a time, rather than all together, so the update can be easily reverted if a problem is detected early.

One solution would be to include some token along with the font data that represents which server software was used to generate the subset, which would be resent with any subsequent requests. That way, the server receiving the second request can know which software it should use to recreate the subset the client already has.

(On the other hand, this solution is essentially a cookie, so maybe nothing new is needed. Or maybe cookies wouldn't work because of browsers' policies of blocking 3rd party cookies - font providers will almost always be 3rd parties. And, I'm also suggesting additional statefulness, which might allow additional tracking, which might be bad - there's a reason for those 3rd party cookie policies. So there might be other better solutions. This also might just not be a problem if servers don't get updated that often - the existing checksum failure would cause the font to be fully resent, and maybe this is rare enough that it's fine. We'd have to consider the situation where a client ends up ping-ponging between two different servers running two different software versions.)

(The range-request method doesn't have this problem because it's just a file - it's identical no matter which software is hosting it.)

**Comment by garretrieger** [comment]
I've been thinking about how we'd solve this if we were running a bunch of patch subset tasks, and I've concluded that a record of the version of the subsetting software wouldn't be all that helpful:
- In general it would be difficult to have two versions of the subsetting library available simultaneously in the same server binary.
- So then if a task gets a request from a client who's font was built with an older version of the subset library then it would need to forward the request to a task still running the previous version.
- This adds additional complexity to the setup, since we now need each task to know what version of the subsetting library all of the other tasks are running.

A simpler solution would be to use sticky load balancing based on the font being requested. ie. all request for a particular font will generally go the the same backend task(s) in a particular region. Which will significantly limit the window where a mismatch could happen.

Given that: 
- the protocol will handle mismatches gracefully (the only harm being more bytes sent then necessary)
- that updates to the subsetter which produce different font binaries are likely to be infrequent.
- techniques like sticky load balancing could be used to mostly solve this in a way that's transparent to the client.
- and the downsides you mentioned with including an arbitrary version token in the clients state.

I don't think we should add the additional version to the clients state.
