### ISSUE TITLE
Describe how patch based transfer by unicode codepoint

### ISSUE THREAD

**Issue by himorin** [w3c/IFT#41]
In [PFE evaluation report document](https://www.w3.org/TR/PFE-evaluation/), "how to send a font data" was described in detail including how font data structure is organized and working, and also evaluations seems to be performed by glyph by glyph (in `glyf`). In this IFT specification, patch based transfer is defined based on Unicode codepoint but not glyph, like
> A subsetted font should be able to render any combination of the codepoints in the subset identically to the original font.

(In theory?) It could be possible to list all relevant glyphs relates to a codepoint, like gathering all GSUB transformed GIDs (transformation such as `liga` for western scripts, or `vert` for CJK), but it seems there is no such detail in this specification yet if this specification really intends to work based on Unicode codepoint but not glyph in `glyf` table.

We would want to know how this patch based transfer works more in detail.

**Comment by garretrieger** [comment]
The specification is intentionally vague with respect to how the subset is formed. This gives flexibility in how font subsetters can be implemented. The only hard requirement  is that the subset produced must be equivalent to the original font when used on any combination of the subset codepoints. This requirement means that a font produced via incremental transfer should render indistinguishably from the original font. As you mentioned this implies that you will need to collect all of the glyph ids that could be accessed via those codepoints (often called glyph closure in subsetting implementations).  Notably this includes all reachable GSUB transformations.

For the evaluation we performed it using both codepoints and glyph ids. The patch subset method was simulated using codepoint sets, while the range request was simulated using glyph id sets. The reason for this difference is that patch subset uses pre-shaping unicode codepoints as the input to derive the subset, while the range request method uses post-shaping glyph id sequences to derive the subset. Range request can work post shaping because the full layout tables are fetched prior to retrieving glyph data. For patch subset this is not possible as the layout tables are built up incrementally along side the glyph data.

I don't think the incremental transfer specification is the right place to record the details of how to implement a font subsetter. We don't want to prescribe the specific details of a subsetter's implementation as there are different approaches which satisfy the equivalence requirement but come with different tradeoffs (eg. subsetting latency vs minimizing subset size). Different incremental font transfer providers may value those tradeoffs differently and choose different implementations. I also expect subsetting technology will continue to advance, with different optimizations and techniques being developed that work well when creating subsets specifically for use in patching.

Unfortunately I'm not aware of any existing comprehensive write-ups that cover the precise details of implementing a subsetter. The good news though is there already exists two high quality open source font subsetting libraries which you could either use as is, or use as a reference to learn how subsetting can be implemented:

- https://github.com/harfbuzz/harfbuzz/blob/main/src/hb-subset.h - The harfbuzz subsetter is a high performance subsetter implemented in C++. The incremental font transfer reference implementation will be using this library for subsetting.
- https://github.com/fonttools/fonttools/blob/main/Lib/fontTools/subset/__init__.py - FontTools subsetter is a python implementation, it's slower than harfbuzz but has some more advanced features (such as support for arbitrary font modifications)

I'll update the spec section on subsetting to link to those for more information on subsetting.

**Comment by garretrieger** [comment]
Just remembered I created a deck giving on overview of the harfbuzz subsetter implementation a while back, you may find this helpful: https://docs.google.com/presentation/d/1RMkpikAUmdIXaz3eEDYFETWfAwnT0Vw8_oC8Ait5xqs/edit#slide=id.p

**Comment by himorin** [comment]
We appreciate your change on text by PR #53, that font subset to be transferred includes glyph substitutions required for specified Unicode codepoints, and we think this text covers point of our concern.
