### ISSUE TITLE
Define functionality in terms of `fetch()` (or otherwise make sure that caching / storage policy matches the rest of the platform).

### ISSUE THREAD

**Issue by pes10k** [w3c/IFT#51]
This issue is part of the PING privacy review w3cping/privacy-request#61

Currently the spec seems to define the document as the lifetime for the results of IFT responses.

The document is an uncommon privacy boundary on the Web; more commonly cache boundaries are defined in terms of eTLD+1, profile, etc. https://github.com/privacycg/storage-partitioning has more information about the effort and goals of partitioning storage and caches.

I think the best fix here would be to define the functionality here in terms of `fetch()`, in which case the proposal would "get" aligning with storage partitioning work "for free." If defining in terms of `fetch()` won't work though, I suggest working with the https://github.com/privacycg/storage-partitioning folks to figure out how to best align this functionality with the privacy-focused partitioning work already happening.

**Comment by garretrieger** [comment]
While this spec is primarily intended for implementation on browsers, it is not solely meant for use in browsers. For example this spec could be used in a mobile phone operating system to incrementally load system fonts as needed. So defining the spec in terms of fetch() which is a browser specific concept is problematic. That's why the spec has been specified as a generic HTTP protocol with no mention made of how storage is handled on the client side.

That said, it is the intention that if this is implemented in a browser the implementation should use standard caching and fetching mechanisms. For example the client state is expected to be stored in the regular http cache and follow all of the usual visibility rules for that cache. So maybe the best path forward is to add an additional section to the spec that adds additional some requirements only for browser based implementations. What do you think?

**Comment by pes10k** [comment]
I think that'd be terrific, specifying the behavior in browsers along the lines you just mentioned, and then noting that implementors should follow similar platform protections (when applicable) in other implementations would address the concern. Thanks!

**Comment by litherum** [comment]
> defining the spec in terms of fetch() which is a browser specific concept is problematic.

I don't think this is necessarily true. W3C specs are not browser-specific; instead they are designed for "user agents." For example, there are plenty of CSS engines which are not browsers. In [the spec for fetch()](https://fetch.spec.whatwg.org), the word "browser" only occurs in non-normative text. As long as fetch() is sufficiently generic (which I believe it is), defining IFT in terms of it seems reasonable.

**Comment by jyasskin** [comment]
You could specify IFT based on a call to https://fetch.spec.whatwg.org/#concept-fetch, but then say that a UA with only a simple HTTP stack can treat that as a call into whatever stack they have. The key benefit to writing against the Fetch API is that you get a rigorous definition of the parameters to the call, so that you're not accidentally leaving one of them ambiguous for clients that care.

**Comment by garretrieger** [comment]
That sounds good, that should work.

**Comment by svgeesus** [comment]
@pes10k so, the **"privacy-needs-resolution"** tag could be removed on this closed issue?

**Comment by pes10k** [comment]
done
