### ISSUE TITLE
Support OpenType Features (discretionary)

### ISSUE THREAD

**Issue by davelab6** [w3c/IFT#87]
It seems while IFT currently supports transferring OpenType Variations, it doesn't support transferring OpenType Features (that aren't mandatory; I understand those are transferred as part of the data needed to support requested unicode characters. )

For example, say that I have a font file which supports small caps, and I want to start using them.....

https://w3c.github.io/IFT/Overview.html#PatchRequest has

ID | Field Name | Value Type
-- | -- | --
2 | codepoints_have | CompressedSet
3 | codepoints_needed | CompressedSet
4 | indices_have | CompressedSet
5 | indices_needed | CompressedSet
**6** | **axis_space_have** | **AxisSpace**
**7** | **axis_space_needed** | **AxisSpace**

I expect

ID | Field Name | Value Type
-- | -- | --
2 | codepoints_have | CompressedSet
3 | codepoints_needed | CompressedSet
4 | indices_have | CompressedSet
5 | indices_needed | CompressedSet
6 | axis_space_have | AxisSpace
7 | axis_space_needed | AxisSpace
**9** | **features_have** | **FeatureList**
**10** | **features_needed** | **FeatureList**

(Possibly this related practically to adding Font Collection support #28)

**Comment by garretrieger** [comment]
As currently specified the requirement is for the patch font to contain all features found in the original font. This is enforced by the https://w3c.github.io/IFT/Overview.html#font-subset definition's requirement for identical rendering with any optional features.

If we do want to have features selectable, then we probably need to change the rendering equivalence requirement to only apply to a predefined list of required features. With any features beyond that needing to be explicitly asked for (likely with an option to say you just want them all)

**Comment by tiroj** [comment]
> We need a good "default feature set" though

Do we?

What is the method for determining whether a feature is used or not? It would seem to be in keeping with the concept of IFT to provide only those features and associated glyphs required to render the document as specified in the CSS.

**Comment by svgeesus** [comment]
Discussed on [17 May 2022 call](https://www.w3.org/2022/05/17-webfonts-minutes.html#t04)

**Comment by tiroj** [comment]
Further to the discussion in today’s call, here is the summary of my recommendations re. defining a set of default features, as requested by Vlad.

The default set of features called for any given codepoint should include all features used for standard script and text shaping. In practice, I think this means all OTL features that are specified as on by default (regardless of whether a user my opt to turn them off). The list could be subdivided into script shaping features, language system specific features, and default typographic display features, but it is the ‘on by default’ status that makes them a suitable default set.

That said, the OT/OFF feature registry is not always explicit about the default state of each feature. This is something that I have wanted to review for a long time, adding default state and state change indicators as a new data item for each feature description in the registry, rather than relying on interpretation of the feature description text. Back in 2014, I took a run at classifying features and assigning a state indicator to each in the form

1/0.   On by default and cannot be turned off
1/1    On by default and can be turned off
0/1    Off by default but can be turned on

This list is available as part of the document [Enabling Typography: towards a general model of OpenType Layout](http://tiro.com/John/Enabling_Typography_(OTL).pdf).

[Note that the list in that document should be compared with the current OT/OFF feature registry, as some new features may have been registered since 2014.]

There some special conditions that apply to some features, e.g. some that are specifically relevant to vertical layout, and as discussed during the call the Fractions (frac) feature can be triggered in HarfBuzz by the presence of U+2044 between numerals.

**Comment by garretrieger** [comment]
I've created a draft (#95) of the changes to allow features to be optionally transferred. As discussed in our last WG call this includes a list of features which are considered "default" and are always sent. For this draft I used the list of "default on" features from the paper @tiroj provided crossed with the list of registered features in the [open type spec](https://docs.microsoft.com/en-us/typography/opentype/spec/featuretags).

There was a small number of features in the opentype spec which did not have a classification in the paper. These are:

aalt, Access All Alternates
chws, Contextual Half-width Spacing
dtls, Dotless Forms
flac, Flattened accent forms
rvrn, Required Variation Alternates
size, Optical size
ssty, Math script style alternates
vchw, Vertical Contextual Half-width Spacing
vrtr, Vertical Alternates for Rotation

John, would you be able to review these uncategorized features and for each let me know if we should treat them as included by default or not?

**Comment by garretrieger** [comment]
Based on feedback from Kalhed plus adding in the list of hb-subset defaults the set of unclassified feature tags is now:

aalt, Access All Alternates
chws, Contextual Half-width Spacing
size, Optical size
vchw, Vertical Contextual Half-width Spacing
vrtr, Vertical Alternates for Rotation

**Comment by tiroj** [comment]
_aalt_
This is a UI hack feature registered by Adobe early in OT history; personally, I think it is a silly feature, not even needed for the original intent and not useful in text layout.

_dtls flac ssty_
These are specific to math layout, so would be essential for fonts that include a MATH table, but not for any other fonts.

_chws vchw vrtr_
These are CJK font features. I agree with Khaled that these should probably be available by default for such fonts, but since these are specific to certain kinds of discretionary layout perhaps they could be algorithmically available?

_size_
Another silly feature from the early days of OT feature registration, when features were defined without any effort to implement them. To my knowledge, this GPOS table data hack to store optical size selection information was never supported in any software, and barely supported in any fonts. It has been superceded by variable fonts and STAT table information.

_rvrn_
This is a new feature, defined since my 2014 document. This feature is specific to variable fonts, and should be available by default. It bepossible to make this available algorithmically for variable fonts only, but one would need to come up with a reliable identification of a variable font that could include variations only in GSUB as demonstrated by Adam Twardoch.

**Comment by garretrieger** [comment]
Ok here's what I plan to do:

aalt, size -> non default.
ftls, flac, ssty -> default. Since they are required for math fonts to work properly and shouldn't really be found in non-math fonts.
chws, vchw, vrtr -> default, since we have also defaulted the other vertical rendering features.
rvrn -> default
